# Generated by Django 5.2.5 on 2026-01-04 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_videolesson_thumbnail'),
        ('groups', '0004_group_deadline_date_group_deadline_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в тенге', max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Можно ли покупать курс онлайн', verbose_name='Продажи активны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_settings', to='content.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Цена курса',
                'verbose_name_plural': 'Цены курсов',
                'db_table': 'payments_course_price',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Токен')),
                ('email', models.EmailField(max_length=254, verbose_name='Email покупателя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('kaspi_payment_id', models.CharField(blank=True, help_text='ID платежа в системе Kaspi', max_length=100, verbose_name='Kaspi Payment ID')),
                ('kaspi_qr_token', models.CharField(blank=True, help_text='Токен для генерации QR-кода', max_length=255, verbose_name='Kaspi QR Token')),
                ('kaspi_qr_payload', models.TextField(blank=True, help_text='Данные для отображения QR-кода', verbose_name='Kaspi QR Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Истекает')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='content.course', verbose_name='Курс')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='groups.group', verbose_name='Группа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'payments_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='payments_or_status_4fb679_idx'), models.Index(fields=['email', 'status'], name='payments_or_email_fa60c6_idx'), models.Index(fields=['kaspi_payment_id'], name='payments_or_kaspi_p_2cd54a_idx')],
            },
        ),
    ]
