# Generated by Django 5.2.5 on 2025-11-06 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата зачисления')),
                ('progress_percentage', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, verbose_name='Прогресс (%)')),
                ('completed_lessons_count', models.PositiveIntegerField(default=0, verbose_name='Завершено уроков')),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последняя активность')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.course', verbose_name='Курс')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='groups.group', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Зачисление на курс',
                'verbose_name_plural': 'Зачисления на курсы',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='progress_co_user_id_32dcce_idx'), models.Index(fields=['course', 'is_active'], name='progress_co_course__8e08a6_idx'), models.Index(fields=['-enrolled_at'], name='progress_co_enrolle_242cdb_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Завершен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершение')),
                ('available_at', models.DateTimeField(blank=True, help_text='Когда урок станет доступен (учитывается задержка)', null=True, verbose_name='Доступен с')),
                ('completion_data', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация (баллы теста, оценка задания и т.д.)', verbose_name='Данные о завершении')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогресс по урокам',
                'ordering': ['lesson__module__order', 'lesson__order'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='progress_le_user_id_8c8ec5_idx'), models.Index(fields=['user', 'is_completed'], name='progress_le_user_id_734ee4_idx'), models.Index(fields=['lesson', 'is_completed'], name='progress_le_lesson__1aa494_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.PositiveIntegerField(default=0, verbose_name='Текущая позиция (секунды)')),
                ('watch_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент просмотра')),
                ('total_watch_time', models.PositiveIntegerField(default=0, help_text='Суммарное время всех просмотров', verbose_name='Общее время просмотра (секунды)')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Завершен')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='content.videolesson', verbose_name='Видео-урок')),
            ],
            options={
                'verbose_name': 'Прогресс видео',
                'verbose_name_plural': 'Прогресс видео',
                'indexes': [models.Index(fields=['user', 'video_lesson'], name='progress_vi_user_id_022123_idx'), models.Index(fields=['user', 'is_completed'], name='progress_vi_user_id_fdc563_idx')],
                'unique_together': {('user', 'video_lesson')},
            },
        ),
    ]
