# Generated by Django 5.2.5 on 2025-11-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '❌ Не оплачено'), ('paid', '✅ Оплачено'), ('trial', '🎁 Пробный доступ')], db_index=True, default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
