# Generated by Django 5.2.5 on 2025-11-07 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_courseenrollment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='False = удален из группы или дедлайн истек', null=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент прохождения'),
        ),
    ]
