# Generated by Django 5.2.5 on 2025-11-07 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_remove_courseenrollment_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videoprogress',
            name='progress_vi_user_id_fdc563_idx',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='total_watch_time',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='watch_count',
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало просмотра'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='watch_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Максимальный процент просмотра видео', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент просмотра'),
        ),
    ]
