# Generated by Django 5.2.5 on 2026-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_remove_videoprogress_progress_vi_user_id_fdc563_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при завершении'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_user_agent',
            field=models.TextField(blank=True, default='', verbose_name='Браузер при завершении'),
        ),
    ]
