# Generated by Django 5.2.5 on 2025-11-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone'),
        ('groups', '0004_group_deadline_date_group_deadline_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым у инструктора есть доступ', related_name='assigned_instructors', to='groups.group', verbose_name='Назначенные группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('instructor', 'Инструктор'), ('super_instructor', 'Супер-инструктор'), ('manager', 'Менеджер'), ('super_manager', 'Супер-менеджер')], db_index=True, default='student', help_text='Роль пользователя в системе', max_length=50, verbose_name='Роль'),
        ),
    ]
