# Generated by Django 5.2.5 on 2025-12-09 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_assigned_groups_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgovAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Sigex QR ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание подписи'), ('signed', 'Подписано'), ('completed', 'Завершено'), ('expired', 'Истекло'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egov_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия eGov авторизации',
                'verbose_name_plural': 'Сессии eGov авторизации',
                'db_table': 'egov_auth_sessions',
            },
        ),
    ]
