# Generated by Django 5.2.5 on 2026-03-10 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='attempted_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Попытка входа (email)'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('login_failed', 'Неудачный вход'), ('lesson_completed', 'Урок завершён'), ('quiz_completed', 'Тест завершён'), ('assignment_submitted', 'Задание отправлено')], db_index=True, max_length=30, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
