# Generated by Django 5.2.5 on 2026-03-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_login_failed_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('egov', 'eGov')], db_index=True, default='email', max_length=10, verbose_name='Метод регистрации'),
        ),
    ]
