# Generated by Django 5.2.5 on 2025-11-26 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduates', '0003_alter_graduate_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
                ('role_assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Роль назначена')),
                ('total_groups_led', models.PositiveIntegerField(default=0, verbose_name='Групп вел')),
                ('total_students_taught', models.PositiveIntegerField(default=0, verbose_name='Студентов обучил')),
                ('total_graduates', models.PositiveIntegerField(default=0, verbose_name='Выпустил студентов')),
                ('total_assignments_reviewed', models.PositiveIntegerField(default=0, verbose_name='ДЗ проверено')),
                ('total_assignments_passed', models.PositiveIntegerField(default=0, verbose_name='ДЗ зачтено')),
                ('total_assignments_rejected', models.PositiveIntegerField(default=0, verbose_name='ДЗ на доработку')),
                ('average_score_given', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Средняя оценка')),
                ('registered_at', models.DateTimeField(verbose_name='Дата регистрации')),
                ('dossier_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Досье создано')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('groups_history', models.JSONField(default=list, help_text='Все группы которые вел', verbose_name='История групп')),
                ('reviews_summary', models.JSONField(default=dict, help_text='Статистика по проверкам ДЗ', verbose_name='Сводка проверок')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_dossier', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Досье инструктора',
                'verbose_name_plural': 'Досье инструкторов',
                'ordering': ['-dossier_created_at'],
                'indexes': [models.Index(fields=['email'], name='dossier_ins_email_8a6575_idx'), models.Index(fields=['-total_graduates'], name='dossier_ins_total_g_cec3b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('course_title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('course_label', models.CharField(blank=True, max_length=50, verbose_name='Код курса')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('instructor_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО инструктора')),
                ('instructor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email инструктора')),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='dossier/certificates/%Y/%m/', verbose_name='Файл сертификата')),
                ('enrolled_at', models.DateTimeField(verbose_name='Дата зачисления')),
                ('completed_at', models.DateTimeField(verbose_name='Дата завершения обучения')),
                ('graduated_at', models.DateTimeField(verbose_name='Дата выпуска')),
                ('dossier_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Досье создано')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Итоговая оценка (%)')),
                ('total_lessons_completed', models.PositiveIntegerField(verbose_name='Уроков завершено')),
                ('total_study_days', models.PositiveIntegerField(verbose_name='Дней на обучение')),
                ('average_quiz_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Средний балл за тесты (%)')),
                ('lessons_history', models.JSONField(default=list, help_text='Все пройденные уроки с датами', verbose_name='История уроков')),
                ('quizzes_history', models.JSONField(default=list, help_text='Все попытки тестов с ответами', verbose_name='История тестов')),
                ('assignments_history', models.JSONField(default=list, help_text='Все ДЗ с оценками и feedback', verbose_name='История ДЗ')),
                ('modules_history', models.JSONField(default=list, help_text='Даты завершения модулей', verbose_name='История модулей')),
                ('graduate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier', to='graduates.graduate', verbose_name='Запись о выпуске')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Досье студента',
                'verbose_name_plural': 'Досье студентов',
                'ordering': ['-graduated_at'],
                'indexes': [models.Index(fields=['certificate_number'], name='dossier_stu_certifi_fd39db_idx'), models.Index(fields=['iin'], name='dossier_stu_iin_05f876_idx'), models.Index(fields=['email'], name='dossier_stu_email_19e88f_idx'), models.Index(fields=['-graduated_at'], name='dossier_stu_graduat_a92473_idx')],
            },
        ),
    ]
