# Generated by Django 5.2.5 on 2026-01-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdossier',
            name='certificate_file',
        ),
    ]
