# Generated by Django 5.2.5 on 2026-01-23 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduates', '0003_alter_graduate_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('internal', 'Выдан системой'), ('external', 'Внешний')], db_index=True, default='internal', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('pending', 'Генерируется'), ('ready', 'Готов'), ('error', 'Ошибка генерации')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер сертификата')),
                ('holder_name', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('course_title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('group_name', models.CharField(blank=True, max_length=255, verbose_name='Название группы')),
                ('file_without_stamp', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='Без печати')),
                ('file_with_stamp', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='С печатью')),
                ('issued_at', models.DateField(db_index=True, verbose_name='Дата выдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('graduate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='graduates.graduate', verbose_name='Выпуск')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_at', '-created_at'],
                'indexes': [models.Index(fields=['number'], name='certificate_number_94bd9f_idx'), models.Index(fields=['source', 'status'], name='certificate_source_839c47_idx'), models.Index(fields=['-issued_at'], name='certificate_issued__fd4b97_idx')],
            },
        ),
    ]
