# Generated by Django 5.2.5 on 2026-01-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('content', '0003_videolesson_thumbnail'),
        ('graduates', '0004_remove_graduate_graduates_g_certifi_9eb89b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_course_title', models.CharField(help_text='Название для сертификата (может отличаться от названия на сайте)', max_length=500, verbose_name='Полное название курса')),
                ('issue_date_label', models.CharField(blank=True, default='Дата выдачи:', help_text='Оставьте пустым, если дата не нужна', max_length=100, verbose_name='Текст даты выдачи')),
                ('stamp_css_class', models.CharField(default='stamp-img-1', help_text='Например: stamp-img-1, stamp-img-2', max_length=50, verbose_name='CSS класс печати')),
                ('signature_css_class', models.CharField(default='aft-img-1', help_text='Например: aft-img-1, aft-img-2', max_length=50, verbose_name='CSS класс подписи')),
                ('signer_name', models.CharField(help_text='Например: Иванов И.И.', max_length=255, verbose_name='ФИО подписавшего')),
                ('signer_position', models.CharField(help_text='Например: Генеральный директор', max_length=255, verbose_name='Должность подписавшего')),
                ('certificate_title', models.CharField(default='СЕРТИФИКАТ', help_text='Для успешно завершивших', max_length=100, verbose_name='Заголовок сертификата')),
                ('attended_title', models.CharField(default='СПРАВКА', help_text='Для не прошедших курс', max_length=100, verbose_name='Заголовок "Прослушал"')),
                ('completion_text', models.CharField(default='успешно завершил(а) курс', help_text='Для сертификата', max_length=255, verbose_name='Текст завершения')),
                ('attended_text', models.CharField(default='прослушал(а) курс', help_text='Для справки о прослушивании', max_length=255, verbose_name='Текст прослушивания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон сертификата',
                'verbose_name_plural': 'Шаблоны сертификатов',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('certificate', 'Сертификат'), ('attended', 'Прослушал')], db_index=True, default='certificate', max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='completion_text',
            field=models.CharField(default='успешно завершил(а) курс', max_length=255, verbose_name='Текст завершения'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='document_title',
            field=models.CharField(default='СЕРТИФИКАТ', max_length=100, verbose_name='Заголовок документа'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date_label',
            field=models.CharField(blank=True, default='Дата выдачи:', max_length=100, verbose_name='Текст даты выдачи'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_css_class',
            field=models.CharField(default='aft-img-1', max_length=50, verbose_name='CSS класс подписи'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО подписавшего'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signer_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность подписавшего'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='stamp_css_class',
            field=models.CharField(default='stamp-img-1', max_length=50, verbose_name='CSS класс печати'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_title',
            field=models.CharField(max_length=500, verbose_name='Название курса'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_type'], name='certificate_certifi_0e5b95_idx'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='content.course', verbose_name='Курс'),
        ),
    ]
