# Generated by Django 5.2.5 on 2026-01-25 09:44

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatetemplate_certificate_certificate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file_with_stamp',
            field=models.FileField(blank=True, null=True, upload_to=certificates.models.certificate_upload_path, verbose_name='С печатью'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_without_stamp',
            field=models.FileField(blank=True, null=True, upload_to=certificates.models.certificate_upload_path, verbose_name='Без печати'),
        ),
    ]
