# Generated by Django 5.2.5 on 2026-01-25 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_file_with_stamp_and_more'),
        ('content', '0003_videolesson_thumbnail'),
        ('graduates', '0004_remove_graduate_graduates_g_certifi_9eb89b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='content.course', verbose_name='Курс'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'course'], name='certificate_user_id_2a7ce8_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), ('user__isnull', False)), fields=('user', 'course', 'certificate_type'), name='unique_user_course_certificate_type'),
        ),
    ]
