# Generated by Django 5.2.5 on 2025-10-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='timecodes',
            field=models.JSONField(blank=True, help_text='JSON массив таймкодов: [{"time": "00:00", "title": "Введение"}]', null=True, verbose_name='Таймкоды'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность в секундах', null=True, verbose_name='Длительность видео (сек)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube, Vimeo и т.д.', null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/%Y/%m/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Тип файла')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Материал урока',
                'verbose_name_plural': 'Материалы уроков',
                'db_table': 'lesson_materials',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
