# Generated by Django 5.2.5 on 2025-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_timecodes_lesson_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длительность (часы)'),
        ),
        migrations.AddField(
            model_name='course',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Label'),
        ),
    ]
