# Generated by Django 5.2.5 on 2025-11-03 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_course_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_lessons_count',
            field=models.PositiveIntegerField(default=0, help_text='Кешированное количество завершенных уроков', verbose_name='Завершено уроков'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Когда студент последний раз взаимодействовал с курсом', null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Кешированный процент прогресса', max_digits=5, verbose_name='Прогресс (%)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Видео урок'), ('text', 'Текстовый урок'), ('quiz', 'Тест'), ('assignment', 'Домашнее задание')], db_index=True, default='video', max_length=20, verbose_name='Тип урока'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completion_data',
            field=models.JSONField(blank=True, help_text='Дополнительные данные о завершении урока', null=True, verbose_name='Данные завершения'),
        ),
        migrations.CreateModel(
            name='AssignmentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(help_text='Детальное описание того, что нужно сделать', verbose_name='Инструкции к заданию')),
                ('require_text', models.BooleanField(default=False, help_text='Студент должен заполнить текстовое поле', verbose_name='Текст обязателен')),
                ('require_file', models.BooleanField(default=True, help_text='Студент должен загрузить файл', verbose_name='Файл обязателен')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Максимальная оценка за задание', verbose_name='Максимальный балл')),
                ('deadline', models.DateTimeField(blank=True, help_text='Крайний срок сдачи (оставьте пустым если нет дедлайна)', null=True, verbose_name='Дедлайн')),
                ('allow_late_submission', models.BooleanField(default=True, help_text='Можно ли сдать задание после дедлайна', verbose_name='Разрешить опоздание')),
                ('late_penalty_percent', models.PositiveIntegerField(default=0, help_text='Процент снижения оценки за просрочку', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Штраф за опоздание (%)')),
                ('allow_resubmission', models.BooleanField(default=True, help_text='Можно ли отправлять задание на доработку и пересдачу', verbose_name='Разрешить пересдачу')),
                ('max_resubmissions', models.PositiveIntegerField(default=3, help_text='Максимальное количество попыток сдачи (0 = неограничено)', verbose_name='Максимум пересдач')),
                ('allowed_file_types', models.CharField(blank=True, help_text='Через запятую: pdf,docx,jpg,png (оставьте пустым для любых)', max_length=255, verbose_name='Разрешенные форматы файлов')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Максимальный размер загружаемого файла в мегабайтах', verbose_name='Макс. размер файла (МБ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'assignment'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_content', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'db_table': 'assignment_lessons',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_number', models.PositiveIntegerField(default=1, help_text='Порядковый номер сдачи (при пересдачах увеличивается)', verbose_name='Номер попытки')),
                ('submission_text', models.TextField(blank=True, help_text='Текстовый ответ студента на задание', verbose_name='Текстовый ответ')),
                ('submission_file', models.FileField(blank=True, help_text='Загруженный файл с выполненным заданием', null=True, upload_to='assignments/%Y/%m/', verbose_name='Файл работы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено на проверку'), ('in_review', 'На проверке'), ('revision_requested', 'Требуется доработка'), ('approved', 'Принято'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда создан черновик', verbose_name='Создано')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Когда отправлено на проверку', null=True, verbose_name='Отправлено на проверку')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Когда инструктор проверил', null=True, verbose_name='Проверено')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Оценка за работу (из max_score задания)', null=True, verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, help_text='Общий отзыв инструктора о работе', verbose_name='Отзыв инструктора')),
                ('is_late', models.BooleanField(default=False, help_text='Было ли опоздание при сдаче', verbose_name='Опоздание')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignmentlesson', verbose_name='Домашнее задание')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сдача ДЗ',
                'verbose_name_plural': 'Сдачи ДЗ',
                'db_table': 'assignment_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Текст комментария/сообщения', verbose_name='Сообщение')),
                ('is_instructor', models.BooleanField(default=False, help_text='Комментарий от инструктора или от студента', verbose_name='От инструктора')),
                ('is_read', models.BooleanField(default=False, help_text='Прочитано ли сообщение получателем', verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.assignmentsubmission', verbose_name='Сдача ДЗ')),
            ],
            options={
                'verbose_name': 'Комментарий к ДЗ',
                'verbose_name_plural': 'Комментарии к ДЗ',
                'db_table': 'assignment_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Минимальный процент правильных ответов для прохождения', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Проходной балл (%)')),
                ('max_attempts', models.PositiveIntegerField(default=2, help_text='Количество попыток для прохождения теста', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум попыток')),
                ('retry_delay_hours', models.PositiveIntegerField(default=24, help_text='Время блокировки после неудачной попытки', verbose_name='Задержка между попытками (часы)')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для неограниченного времени', null=True, verbose_name='Время на тест (минуты)')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Показывать правильные ответы после успешного прохождения', verbose_name='Показывать правильные ответы')),
                ('show_incorrect_only', models.BooleanField(default=True, help_text='Если включено, показывать только те вопросы, на которые ответили неправильно', verbose_name='Показывать только неправильные')),
                ('show_score_immediately', models.BooleanField(default=True, help_text='Показывать результат сразу после завершения теста', verbose_name='Показывать результат сразу')),
                ('shuffle_questions', models.BooleanField(default=False, help_text='Вопросы будут в случайном порядке', verbose_name='Перемешивать вопросы')),
                ('shuffle_answers', models.BooleanField(default=True, help_text='Варианты ответов будут в случайном порядке', verbose_name='Перемешивать ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_content', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'quiz_lessons',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='Порядковый номер попытки для этого студента', verbose_name='Номер попытки')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('passed', 'Пройдена'), ('failed', 'Не пройдена'), ('expired', 'Время истекло')], db_index=True, default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Время окончания теста (если есть ограничение)', null=True, verbose_name='Истекает')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Всего баллов')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Заработано баллов')),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Процент правильных ответов', max_digits=5, null=True, verbose_name='Результат (%)')),
                ('can_retry_at', models.DateTimeField(blank=True, help_text='Время, когда можно будет пройти тест снова', null=True, verbose_name='Доступна следующая попытка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quizlesson', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных ответов')], default='single', max_length=20, verbose_name='Тип вопроса')),
                ('question_text', models.TextField(help_text='Формулировка вопроса', verbose_name='Текст вопроса')),
                ('explanation', models.TextField(blank=True, help_text='Объяснение правильного ответа (показывается после прохождения)', verbose_name='Пояснение к ответу')),
                ('points', models.PositiveIntegerField(default=1, help_text='Количество баллов за правильный ответ', verbose_name='Баллы за вопрос')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения вопроса', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quizlesson', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'db_table': 'quiz_questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='Вариант ответа', max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, help_text='Отметьте если это правильный ответ', verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения ответа', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'quiz_answers',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text='Правильно ли ответил студент', verbose_name='Правильно')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Баллы за этот ответ', verbose_name='Заработано баллов')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.quizattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizquestion', verbose_name='Вопрос')),
                ('selected_answers', models.ManyToManyField(help_text='Ответы, которые выбрал студент', related_name='student_responses', to='courses.quizanswer', verbose_name='Выбранные ответы')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'db_table': 'quiz_responses',
                'ordering': ['attempt', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='TextLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Основной текст урока (поддерживает Markdown или HTML)', verbose_name='Текстовый контент')),
                ('estimated_reading_time', models.PositiveIntegerField(default=5, help_text='Примерное время для прочтения материала', verbose_name='Время на чтение (минуты)')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False, help_text='Автоматически рассчитывается', verbose_name='Количество слов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'text'}, on_delete=django.db.models.deletion.CASCADE, related_name='text_content', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Текстовый урок',
                'verbose_name_plural': 'Текстовые уроки',
                'db_table': 'text_lessons',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_video_id', models.CharField(help_text='ID видео из Vimeo (например: 123456789)', max_length=50, verbose_name='Vimeo Video ID')),
                ('video_duration', models.PositiveIntegerField(help_text='Длительность в секундах', verbose_name='Длительность видео (секунды)')),
                ('completion_threshold', models.PositiveIntegerField(default=90, help_text='Процент просмотра для автоматического завершения урока', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог завершения (%)')),
                ('timecodes', models.JSONField(blank=True, help_text='JSON формат: [{"time": "00:30", "title": "Введение"}, {"time": "05:15", "title": "Основы"}]', null=True, verbose_name='Таймкоды')),
                ('allow_speed_control', models.BooleanField(default=True, verbose_name='Разрешить управление скоростью')),
                ('allow_download', models.BooleanField(default=False, verbose_name='Разрешить скачивание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'video'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Видео урок',
                'verbose_name_plural': 'Видео уроки',
                'db_table': 'video_lessons',
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.PositiveIntegerField(default=0, help_text='Последняя позиция воспроизведения в секундах', verbose_name='Текущая позиция (секунды)')),
                ('watch_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Процент просмотренного видео', max_digits=5, verbose_name='Процент просмотра')),
                ('total_watch_time', models.PositiveIntegerField(default=0, help_text='Суммарное время всех просмотров', verbose_name='Общее время просмотра (секунды)')),
                ('watch_count', models.PositiveIntegerField(default=0, help_text='Сколько раз студент запускал видео', verbose_name='Количество просмотров')),
                ('is_completed', models.BooleanField(default=False, help_text='Достигнут порог завершения', verbose_name='Завершен')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Когда был достигнут порог завершения', null=True, verbose_name='Дата завершения')),
                ('first_watched_at', models.DateTimeField(auto_now_add=True, help_text='Когда студент впервые начал смотреть видео', verbose_name='Первый просмотр')),
                ('last_watched_at', models.DateTimeField(auto_now=True, help_text='Последнее обновление прогресса', verbose_name='Последний просмотр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.videolesson', verbose_name='Видео урок')),
            ],
            options={
                'verbose_name': 'Прогресс видео',
                'verbose_name_plural': 'Прогресс видео',
                'db_table': 'video_progress',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['user', 'assignment', '-created_at'], name='assignment__user_id_028c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='assignment__status_cd5870_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['submission', 'created_at'], name='assignment__submiss_33a69d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-started_at'], name='quiz_attemp_user_id_ab7196_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status'], name='quiz_attemp_status_02023c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['user', 'video_lesson'], name='video_progr_user_id_5e2f99_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['is_completed'], name='video_progr_is_comp_6d321a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('user', 'video_lesson')},
        ),
    ]
