# Generated by Django 5.2.5 on 2025-11-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseenrollment_completed_lessons_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson__module', 'lesson__order'], 'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='access_delay_hours',
            field=models.PositiveIntegerField(default=0, help_text='Через сколько часов урок станет доступен после завершения предыдущего. 0 = доступен сразу', verbose_name='Задержка доступа (часы)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='available_at',
            field=models.DateTimeField(blank=True, help_text='Когда урок станет доступен (с учетом задержки)', null=True, verbose_name='Доступен с'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок урока в модуле', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timecodes',
            field=models.JSONField(blank=True, null=True, verbose_name='Таймкоды'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность видео (сек)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание модуля')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок модуля в курсе', verbose_name='Порядковый номер')),
                ('requires_previous_module', models.BooleanField(default=True, help_text='Модуль доступен только после завершения предыдущего', verbose_name='Требует завершения предыдущего модуля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'modules',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
