# Generated by Django 5.2.5 on 2025-11-06 12:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(help_text='Что нужно сделать для выполнения задания', verbose_name='Инструкции')),
                ('require_text', models.BooleanField(default=True, verbose_name='Требуется текстовый ответ')),
                ('require_file', models.BooleanField(default=False, verbose_name='Требуется файл')),
                ('max_score', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный балл')),
                ('deadline_days', models.PositiveIntegerField(default=7, help_text='Количество дней на выполнение после открытия урока', verbose_name='Дедлайн (дни)')),
                ('allow_late_submission', models.BooleanField(default=True, verbose_name='Разрешить сдачу после дедлайна')),
                ('allow_resubmission', models.BooleanField(default=True, help_text='Студент может сдать повторно после "Требуется доработка"', verbose_name='Разрешить пересдачу')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignmentlesson', to='content.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_number', models.PositiveIntegerField(default=1, verbose_name='Номер попытки')),
                ('submission_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/%Y/%m/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('waiting', '⏳ Ожидает сдачи'), ('in_review', '🔍 На проверке'), ('needs_revision', '✏️ Требуется доработка'), ('failed', '❌ Не зачтено'), ('passed', '✅ Зачтено')], db_index=True, default='in_review', max_length=20, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Балл за выполнение задания', null=True, verbose_name='Балл')),
                ('feedback', models.TextField(blank=True, verbose_name='Обратная связь от преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата сдачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignmentlesson', verbose_name='Задание')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_instructor', models.BooleanField(db_index=True, default=False, verbose_name='От преподавателя')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignments.assignmentsubmission', verbose_name='Сдача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['user', 'assignment', '-submitted_at'], name='assignments_user_id_238dee_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='assignments_status_bf3e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='assignments_assignm_bbafe4_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcomment',
            index=models.Index(fields=['submission', 'created_at'], name='assignments_submiss_3772c3_idx'),
        ),
    ]
