# Generated by Django 5.2.5 on 2025-11-06 11:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Минимальный процент для прохождения теста', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Проходной балл (%)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='0 = неограниченно', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум попыток')),
                ('retry_delay_hours', models.PositiveIntegerField(default=0, help_text='Сколько часов ждать между попытками', verbose_name='Задержка между попытками (часы)')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = без ограничения', verbose_name='Ограничение по времени (минуты)')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='После завершения теста', verbose_name='Показывать правильные ответы')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Перемешивать вопросы')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='Перемешивать ответы')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizlesson', to='content.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Номер попытки')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('timeout', 'Время истекло')], db_index=True, default='in_progress', max_length=20, verbose_name='Статус')),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Результат (%)')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quizlesson', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка прохождения теста',
                'verbose_name_plural': 'Попытки прохождения тестов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', 'Один правильный ответ'), ('multiple_choice', 'Несколько правильных ответов'), ('true_false', 'Верно/Неверно')], default='single_choice', max_length=20, verbose_name='Тип вопроса')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('explanation', models.TextField(blank=True, help_text='Показывается после ответа', verbose_name='Пояснение')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quizlesson', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Заработано баллов')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quizattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quizquestion', verbose_name='Вопрос')),
                ('selected_answers', models.ManyToManyField(related_name='selected_by', to='quizzes.quizanswer', verbose_name='Выбранные ответы')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'ordering': ['attempt', 'question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz', '-started_at'], name='quizzes_qui_user_id_7e13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status', '-started_at'], name='quizzes_qui_status_5427e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
