# Generated by Django 5.2.5 on 2025-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='questions_order',
            field=models.JSONField(blank=True, default=list, help_text='Список ID вопросов в порядке показа студенту', verbose_name='Порядок вопросов'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='answers_order',
            field=models.JSONField(blank=True, default=list, help_text='Список ID ответов в порядке показа студенту', verbose_name='Порядок ответов'),
        ),
    ]
