# Generated by Django 5.2.5 on 2026-01-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt_questions_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='quizzes.quizquestion', verbose_name='Вопрос'),
        ),
    ]
