# Generated by Django 5.2.5 on 2026-01-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_protect_quiz_question_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlesson',
            name='retry_delay_hours',
        ),
        migrations.AddField(
            model_name='quizlesson',
            name='retry_delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Сколько минут ждать между попытками (0 = без задержки)', verbose_name='Задержка между попытками (минуты)'),
        ),
    ]
