# Generated by Django 5.2.5 on 2026-01-30 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quizlesson_retry_delay_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlesson',
            name='is_final_exam',
            field=models.BooleanField(default=False, help_text='Если включено — вопросы агрегируются из промежуточных тестов курса', verbose_name='Итоговый тест'),
        ),
        migrations.AddField(
            model_name='quizlesson',
            name='questions_per_quiz',
            field=models.PositiveIntegerField(default=0, help_text='0 = равномерно распределить. Иначе — фиксированное количество с каждого теста', verbose_name='Вопросов с каждого теста'),
        ),
        migrations.AddField(
            model_name='quizlesson',
            name='total_questions',
            field=models.PositiveIntegerField(default=20, help_text='Сколько вопросов включить в итоговый тест', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество вопросов'),
        ),
    ]
