# Generated by Django 5.2.5 on 2026-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizlesson_is_final_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='completed_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при сдаче'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed_user_agent',
            field=models.TextField(blank=True, default='', verbose_name='Браузер при сдаче'),
        ),
    ]
