# Generated by Django 5.2.5 on 2025-11-06 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Студенты автоматически добавляются в эту группу при зачислении на курс', verbose_name='Дефолтная группа')),
                ('max_students', models.PositiveIntegerField(default=0, help_text='0 = без ограничения', verbose_name='Максимум студентов')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='content.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['course', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('can_grade', models.BooleanField(default=True, help_text='Проверка домашних заданий и тестов', verbose_name='Может проверять задания')),
                ('can_view_progress', models.BooleanField(default=True, help_text='Просмотр прогресса студентов', verbose_name='Может видеть прогресс')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='groups.group', verbose_name='Группа')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_groups', to=settings.AUTH_USER_MODEL, verbose_name='Инструктор')),
            ],
            options={
                'verbose_name': 'Инструктор группы',
                'verbose_name_plural': 'Инструкторы групп',
                'ordering': ['group', '-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Членство в группе',
                'verbose_name_plural': 'Членства в группах',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'is_active'], name='groups_grou_course__5d881a_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'is_default'], name='groups_grou_course__f10a35_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinstructor',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_faf91e_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinstructor',
            index=models.Index(fields=['instructor', 'is_active'], name='groups_grou_instruc_1f1786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinstructor',
            unique_together={('group', 'instructor')},
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_f7e3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'is_active'], name='groups_grou_user_id_bd45cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user', 'is_active')},
        ),
    ]
