# Generated by Django 5.2.5 on 2025-11-06 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', '-is_default', '-is_graduates_group', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='deadline_days',
            field=models.PositiveIntegerField(default=0, help_text='Количество дней на обучение. 0 = бессрочно', verbose_name='Дедлайн группы (дни)'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_graduates_group',
            field=models.BooleanField(db_index=True, default=False, help_text='Автоматическая группа для завершивших обучение', verbose_name='Группа выпускников'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Требуется оплата для доступа', verbose_name='Платная группа'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, help_text='Для групп выпускников - из какой группы они пришли', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduates_groups', to='groups.group', verbose_name='Родительская группа'),
        ),
        migrations.AddField(
            model_name='group',
            name='referral_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Уникальная ссылка для приглашения в группу', unique=True, verbose_name='Реферальный токен'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='enrolled_via_referral',
            field=models.BooleanField(default=False, help_text='Пользователь зашел по реферальной ссылке группы', verbose_name='Через реферальную ссылку'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='personal_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Индивидуальный дедлайн для этого студента', null=True, verbose_name='Персональный дедлайн'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Группа для самооплаты курса (одна на курс)', verbose_name='Дефолтная группа'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['referral_token'], name='groups_grou_referra_dc39c3_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['personal_deadline_at'], name='groups_grou_persona_7f1aec_idx'),
        ),
    ]
