# Generated by Django 5.2.5 on 2025-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', '-is_default', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_graduates_group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='parent_group',
        ),
    ]
