# Generated by Django 5.2.5 on 2025-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('groups', '0003_alter_group_options_remove_group_is_graduates_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deadline_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Для B2B групп: общий дедлайн для всех студентов', null=True, verbose_name='Фиксированная дата дедлайна'),
        ),
        migrations.AddField(
            model_name='group',
            name='deadline_type',
            field=models.CharField(choices=[('personal_days', 'Персональные дни'), ('fixed_date', 'Фиксированная дата')], default='personal_days', help_text='Персональные дни (B2C) или фиксированная дата (B2B)', max_length=20, verbose_name='Тип дедлайна'),
        ),
        migrations.AlterField(
            model_name='group',
            name='deadline_days',
            field=models.PositiveIntegerField(default=90, help_text='Для дефолтных групп (B2C): количество дней на обучение', verbose_name='Дедлайн в днях'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Группа для самооплаты курса (B2C, одна на курс)', verbose_name='Дефолтная группа'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['deadline_date'], name='groups_grou_deadlin_9dc98a_idx'),
        ),
    ]
