# Generated by Django 5.2.5 on 2026-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_deadline_date_group_deadline_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='final_exam_date',
            field=models.DateField(blank=True, help_text='Для бесплатных групп: дата проведения итогового теста', null=True, verbose_name='Дата итогового теста'),
        ),
        migrations.AddField(
            model_name='group',
            name='final_exam_end_time',
            field=models.TimeField(blank=True, help_text='Время закрытия теста (например, 17:00)', null=True, verbose_name='Окончание итогового теста'),
        ),
        migrations.AddField(
            model_name='group',
            name='final_exam_start_time',
            field=models.TimeField(blank=True, help_text='Время открытия теста (например, 15:00)', null=True, verbose_name='Начало итогового теста'),
        ),
    ]
