# Generated by Django 5.2.5 on 2025-11-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('groups', '0003_alter_group_options_remove_group_is_graduates_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата выпуска')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, help_text='Средний балл по всем тестам и заданиям', max_digits=5, verbose_name='Итоговая оценка (%)')),
                ('total_lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Уроков завершено')),
                ('average_quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Средний балл за тесты')),
                ('total_study_days', models.PositiveIntegerField(default=0, help_text='От зачисления до завершения', verbose_name='Дней на обучение')),
                ('certificate_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Номер сертификата')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='Файл сертификата')),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи сертификата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduates', to='content.course', verbose_name='Курс')),
                ('group', models.ForeignKey(blank=True, help_text='Из какой группы выпустился', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduates', to='groups.group', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
                'ordering': ['-graduated_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduateAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('perfect_score', '💯 Идеальный результат'), ('fast_learner', '⚡ Быстрое обучение'), ('best_student', '🏆 Лучший студент'), ('helpful', '🤝 Помощь другим'), ('active', '🔥 Активный студент')], max_length=50, verbose_name='Тип достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='graduates.graduate', verbose_name='Выпускник')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='graduate',
            index=models.Index(fields=['user', 'course'], name='graduates_g_user_id_5d6143_idx'),
        ),
        migrations.AddIndex(
            model_name='graduate',
            index=models.Index(fields=['course', '-graduated_at'], name='graduates_g_course__6dddc7_idx'),
        ),
        migrations.AddIndex(
            model_name='graduate',
            index=models.Index(fields=['certificate_number'], name='graduates_g_certifi_9eb89b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graduate',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='graduateachievement',
            unique_together={('graduate', 'achievement_type')},
        ),
    ]
