# Generated by Django 5.2.5 on 2025-11-14 13:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_module_requires_previous_module'),
        ('graduates', '0001_initial'),
        ('groups', '0004_group_deadline_date_group_deadline_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduate',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Выпускник', 'verbose_name_plural': 'Выпускники'},
        ),
        migrations.RemoveIndex(
            model_name='graduate',
            name='graduates_g_course__6dddc7_idx',
        ),
        migrations.AddField(
            model_name='graduate',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2025, 11, 14, 13, 33, 18, 492905, tzinfo=datetime.timezone.utc), help_text='Когда достиг 100% прогресса', verbose_name='Дата завершения обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='completion_details',
            field=models.JSONField(blank=True, default=dict, help_text='Даты прохождения модулей, уроков, попытки тестов', verbose_name='Детали прохождения'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_students', to=settings.AUTH_USER_MODEL, verbose_name='Выпустил (менеджер)'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Закончил обучение (ожидает выпуска)'), ('graduated', '🎓 Выпущен'), ('rejected', '❌ Отклонен')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='final_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Средний балл по всем тестам', max_digits=5, verbose_name='Итоговая оценка (%)'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='graduated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда менеджер подтвердил выпуск', null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа в которой проходил обучение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduates', to='groups.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания менеджера'),
        ),
        migrations.AddIndex(
            model_name='graduate',
            index=models.Index(fields=['status', '-completed_at'], name='graduates_g_status_19c813_idx'),
        ),
        migrations.AddIndex(
            model_name='graduate',
            index=models.Index(fields=['group', 'status'], name='graduates_g_group_i_ccd3c9_idx'),
        ),
    ]
