# Generated by Django 5.2.5 on 2025-11-14 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_alter_graduate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='completed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Когда достиг 100% прогресса', verbose_name='Дата завершения обучения'),
        ),
        migrations.DeleteModel(
            name='GraduateAchievement',
        ),
    ]
