# Generated by Django 5.2.5 on 2026-01-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_alter_graduate_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='graduate',
            name='graduates_g_certifi_9eb89b_idx',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='certificate_issued_at',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='certificate_number',
        ),
    ]
