# Generated by Django 5.2.5 on 2025-11-06 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('video', '📹 Видео'), ('text', '📄 Текст'), ('quiz', '❓ Тест'), ('assignment', '📝 Домашнее задание')], db_index=True, max_length=20, verbose_name='Тип урока')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание урока')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('access_delay_hours', models.PositiveIntegerField(default=0, help_text='Через сколько часов после предыдущего урока откроется этот', verbose_name='Задержка доступа (часы)')),
                ('requires_previous_completion', models.BooleanField(default=True, verbose_name='Требует завершения предыдущего урока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('label', models.CharField(blank=True, help_text='Например: "Базовый курс"', max_length=100, verbose_name='Метка курса')),
                ('duration', models.CharField(blank=True, help_text='Например: "3 месяца"', max_length=100, verbose_name='Длительность')),
                ('description', models.TextField(blank=True, verbose_name='Описание курса')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/%Y/%m/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, help_text='Внешняя ссылка на материал', verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='content.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Материал к уроку',
                'verbose_name_plural': 'Материалы к уроку',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание модуля')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('requires_previous_module', models.BooleanField(default=True, help_text='Студент должен завершить предыдущий модуль', verbose_name='Требует завершения предыдущего модуля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module', verbose_name='Модуль'),
        ),
        migrations.CreateModel(
            name='TextLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое урока')),
                ('estimated_reading_time', models.PositiveIntegerField(default=5, help_text='Примерное время на чтение', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время чтения (минуты)')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='textlesson', to='content.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Текстовый урок',
                'verbose_name_plural': 'Текстовые уроки',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_video_id', models.CharField(help_text='Например: 123456789', max_length=100, verbose_name='ID видео Vimeo')),
                ('video_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность видео (секунды)')),
                ('completion_threshold', models.PositiveIntegerField(default=90, help_text='Процент просмотра для завершения урока', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Порог завершения (%)')),
                ('timecodes', models.JSONField(blank=True, default=list, help_text='Список таймкодов: [{"time": 120, "label": "Введение"}]', verbose_name='Таймкоды')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videolesson', to='content.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Видео-урок',
                'verbose_name_plural': 'Видео-уроки',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', '-created_at'], name='content_cou_is_acti_e63183_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='content_mod_course__07037a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='content_les_module__c210ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='content_les_lesson__2f0b53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
    ]
