# Generated by Django 5.2.5 on 2025-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='requires_previous_module',
            field=models.BooleanField(default=True, help_text='⚠️ НЕ ИСПОЛЬЗУЕТСЯ. Логика доступности работает на уровне уроков.', verbose_name='Требует завершения предыдущего модуля'),
        ),
    ]
