# Generated by Django 5.2.5 on 2025-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_module_requires_previous_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1280x720px', null=True, upload_to='video_thumbnails/%Y/%m/', verbose_name='Обложка видео'),
        ),
    ]
