# Generated by Django 5.2.5 on 2026-01-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_videolesson_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project_url',
            field=models.URLField(blank=True, help_text='Ссылка на оригинальный проект (Notion, Confluence и т.д.)', max_length=500, verbose_name='Ссылка на проджаник'),
        ),
    ]
