# Generated by Django 5.2.5 on 2026-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_course_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Заполняется автоматически из Vimeo', null=True, verbose_name='Длительность видео (секунды)'),
        ),
    ]
