# Generated by Django 5.2.5 on 2026-02-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_video_duration_auto_from_vimeo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='requires_previous_module',
        ),
    ]
