# Generated by Django 5.2.5 on 2025-10-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(db_index=True, max_length=254, verbose_name='Email получателя')),
                ('email_type', models.CharField(choices=[('email_verification', 'Подтверждение email'), ('password_reset', 'Сброс пароля'), ('payment_success', 'Успешная оплата'), ('newsletter', 'Новостная рассылка'), ('activity_digest', 'Дайджест активности')], db_index=True, max_length=50, verbose_name='Тип письма')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sendpulse_response', models.JSONField(blank=True, null=True, verbose_name='Ответ SendPulse')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог отправки email',
                'verbose_name_plural': 'Логи отправки email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='notificatio_created_c85051_idx'), models.Index(fields=['email_type', 'status'], name='notificatio_email_t_9447d8_idx')],
            },
        ),
    ]
