# Generated by Django 5.2.5 on 2025-11-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_available_email', models.BooleanField(default=True, verbose_name='Email: урок доступен')),
                ('lesson_available_push', models.BooleanField(default=True, verbose_name='Push: урок доступен')),
                ('lesson_available_in_app', models.BooleanField(default=True, verbose_name='In-app: урок доступен')),
                ('homework_accepted_email', models.BooleanField(default=True, verbose_name='Email: ДЗ принято')),
                ('homework_accepted_push', models.BooleanField(default=True, verbose_name='Push: ДЗ принято')),
                ('homework_accepted_in_app', models.BooleanField(default=True, verbose_name='In-app: ДЗ принято')),
                ('homework_needs_revision_email', models.BooleanField(default=True, verbose_name='Email: ДЗ требует доработки')),
                ('homework_needs_revision_push', models.BooleanField(default=True, verbose_name='Push: ДЗ требует доработки')),
                ('homework_needs_revision_in_app', models.BooleanField(default=True, verbose_name='In-app: ДЗ требует доработки')),
                ('course_completed_email', models.BooleanField(default=True, verbose_name='Email: курс завершен')),
                ('course_completed_push', models.BooleanField(default=True, verbose_name='Push: курс завершен')),
                ('course_completed_in_app', models.BooleanField(default=True, verbose_name='In-app: курс завершен')),
                ('promotion_email', models.BooleanField(default=False, verbose_name='Email: акции')),
                ('promotion_push', models.BooleanField(default=False, verbose_name='Push: акции')),
                ('promotion_in_app', models.BooleanField(default=True, verbose_name='In-app: акции')),
                ('bulk_notifications_email', models.BooleanField(default=True, verbose_name='Email: массовые рассылки')),
                ('bulk_notifications_push', models.BooleanField(default=True, verbose_name='Push: массовые рассылки')),
                ('bulk_notifications_in_app', models.BooleanField(default=True, verbose_name='In-app: массовые рассылки')),
                ('support_reply_email', models.BooleanField(default=True, verbose_name='Email: ответ поддержки')),
                ('support_reply_push', models.BooleanField(default=True, verbose_name='Push: ответ поддержки')),
                ('support_reply_in_app', models.BooleanField(default=True, verbose_name='In-app: ответ поддержки')),
                ('system_email', models.BooleanField(default=True, verbose_name='Email: системные')),
                ('system_in_app', models.BooleanField(default=True, verbose_name='In-app: системные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lesson_available', 'Урок доступен'), ('homework_accepted', 'Домашнее задание принято'), ('homework_needs_revision', 'Домашнее задание требует доработки'), ('course_enrolled', 'Зачисление на курс'), ('course_completed', 'Курс завершен'), ('promotion', 'Акция'), ('support_reply', 'Ответ поддержки'), ('bulk_notification', 'Массовая рассылка'), ('system', 'Системное уведомление')], db_index=True, max_length=50, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx')],
            },
        ),
    ]
