# Generated by Django 5.2.5 on 2025-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_notificatio_user_id_427e4b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('registration_completed', 'Регистрация завершена'), ('lesson_available', 'Урок доступен'), ('homework_accepted', 'Домашнее задание принято'), ('homework_needs_revision', 'Домашнее задание требует доработки'), ('course_enrolled', 'Зачисление на курс'), ('course_completed', 'Курс завершен'), ('promotion', 'Акция'), ('support_reply', 'Ответ поддержки'), ('bulk_notification', 'Массовая рассылка'), ('system', 'Системное уведомление')], db_index=True, max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
