# Generated by Django 5.2.5 on 2025-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='registration_completed_email',
            field=models.BooleanField(default=True, verbose_name='Email: регистрация завершена'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='registration_completed_in_app',
            field=models.BooleanField(default=True, verbose_name='In-app: регистрация завершена'),
        ),
    ]
