# Generated by Django 5.2.5 on 2025-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationpreference_registration_completed_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='graduation_email',
            field=models.BooleanField(default=True, verbose_name='Email: выпуск подтвержден'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='graduation_in_app',
            field=models.BooleanField(default=True, verbose_name='In-app: выпуск подтвержден'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='graduation_push',
            field=models.BooleanField(default=True, verbose_name='Push: выпуск подтвержден'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('registration_completed', 'Регистрация завершена'), ('lesson_available', 'Урок доступен'), ('homework_accepted', 'Домашнее задание принято'), ('homework_needs_revision', 'Домашнее задание требует доработки'), ('course_enrolled', 'Зачисление на курс'), ('course_completed', 'Курс завершен'), ('graduation', 'Выпуск подтвержден'), ('promotion', 'Акция'), ('support_reply', 'Ответ поддержки'), ('bulk_notification', 'Массовая рассылка'), ('system', 'Системное уведомление')], db_index=True, max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
